export const API_ENDPOINTS = {
  LOGIN: '/login',
  REGISTER: '/register',
  LOGOUT: '/logout',
  ADDVISIT : "/prouduct/addVisit" ,
  FORGET_PASSWORD: '/forget-password',
  CATEGORIES: '/categorys',
  DIETARY: '/dietary.json',
  BRANDS: '/brands.json',
  PRODUCTS: '/prouduct',
  PRODUCT: '/prouduct',
  PRODUCTSUPLLIER: '/suppliers/prouducts',
  Supplier: '/suppliers',
  USER: '/user',
  RELATED_PRODUCTS: '/related_products.json',
  FLASH_SELL_PRODUCTS: '/products_flash_sell.json',
  BEST_SELLER_PRODUCTS: '/suppliers/best',
  BEST_SELLER_GROCERY_PRODUCTS: '/suppliers/best',
  POPULAR_PRODUCTS: '/products_popular.json',
  MOSTVISITED_PRODUCT: '/prouduct/mostVisited',
  CHIPS_PRODUCTS: '/prouduct/discount',
  POPCORN_JERKY_PRODUCTS: '/products_popcorn_jerky.json',
  FRESH_VEGETABLES_PRODUCTS: '/prouduct',
  SEARCH: '/search.json',
  ORDERS: '/orders.json',
  ORDER: '/order.json',
  ORDER_STATUS: '/order-status.json',
  ADDRESS: '/address.json',
  PAYMENT: '/payment.json',
  CONTACT: '/contact.json',
  SHOP: '/shop.json',
  SHOPS: '/suppliers',
  WISHLIST: '/wishlist.json',
};

export const CDN_BASE_URL = 'http://localhost:3001';
